//
// AuthenticatorTOTPChallengeResponseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** TOTP Challenge response, device is set by get_response_instance */
public struct AuthenticatorTOTPChallengeResponseRequest: Codable, JSONEncodable, Hashable {

    public var component: String? = "ak-stage-authenticator-totp"
    public var code: Int

    public init(component: String? = "ak-stage-authenticator-totp", code: Int) {
        self.component = component
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case component
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(component, forKey: .component)
        try container.encode(code, forKey: .code)
    }
}

