//
// ConsentChallengeResponseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Consent challenge response, any valid response request is valid */
public struct ConsentChallengeResponseRequest: Codable, JSONEncodable, Hashable {

    public var component: String? = "ak-stage-consent"
    public var token: String

    public init(component: String? = "ak-stage-consent", token: String) {
        self.component = component
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case component
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(component, forKey: .component)
        try container.encode(token, forKey: .token)
    }
}

