//
// PatchedOutpostRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Outpost Serializer */
public struct PatchedOutpostRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var type: OutpostTypeEnum?
    public var providers: [Int]?
    /** Select Service-Connection authentik should use to manage this outpost. Leave empty if authentik should not handle the deployment. */
    public var serviceConnection: UUID?
    public var config: [String: AnyCodable]?
    /** Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update. */
    public var managed: String?

    public init(name: String? = nil, type: OutpostTypeEnum? = nil, providers: [Int]? = nil, serviceConnection: UUID? = nil, config: [String: AnyCodable]? = nil, managed: String? = nil) {
        self.name = name
        self.type = type
        self.providers = providers
        self.serviceConnection = serviceConnection
        self.config = config
        self.managed = managed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case providers
        case serviceConnection = "service_connection"
        case config
        case managed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(providers, forKey: .providers)
        try container.encodeIfPresent(serviceConnection, forKey: .serviceConnection)
        try container.encodeIfPresent(config, forKey: .config)
        try container.encodeIfPresent(managed, forKey: .managed)
    }
}

