//
// UserSourceConnection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OAuth Source Serializer */
public struct UserSourceConnection: Codable, JSONEncodable, Hashable {

    public var pk: Int
    public var user: Int
    public var source: Source
    public var created: Date

    public init(pk: Int, user: Int, source: Source, created: Date) {
        self.pk = pk
        self.user = user
        self.source = source
        self.created = created
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
        case user
        case source
        case created
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pk, forKey: .pk)
        try container.encode(user, forKey: .user)
        try container.encode(source, forKey: .source)
        try container.encode(created, forKey: .created)
    }
}

