templateDir: /local/templates/
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  enumUnknownDefaultCase: true
  projectName: authentikClient
  podAuthors: authentik Team
  podHomepage: https://goauthentik.io/
  podSummary: authentik Swift API Client
files:
  README.mustache:
    templateType: SupportingFiles
    destinationFilename: README.md
enumNameMappings:
  2000/09/xmldsig#sha1: _2000_09_xmldsig_sha1
  2001/04/xmldsig-more#sha384: _2001_04_xmldsig_more_sha384
  2001/04/xmlenc#sha256: _2001_04_xmlenc_sha256
  2001/04/xmlenc#sha512: _2001_04_xmlenc_sha512
  1.1:nameid-format:emailAddress: _1_1_nameid_format_emailAddress
  2.0:nameid-format:persistent: _2_0_nameid_format_persistent
  2.0:nameid-format:X509SubjectName: _2_0_nameid_format_X509SubjectName
  2.0:nameid-format:WindowsDomainQualifiedName: _2_0_nameid_format_WindowsDomainQualifiedName
  2.0:nameid-format:transient: _2_0_nameid_format_transient
  2000/09/xmldsig#rsa-sha1: _2000_09_xmldsig_rsa_sha1
  2001/04/xmldsig-more#rsa-sha256: _2001_04_xmldsig_more_rsa_sha256
  2001/04/xmldsig-more#rsa-sha384: _2001_04_xmldsig_more_rsa_sha384
  2001/04/xmldsig-more#rsa-sha512: _2001_04_xmldsig_more_rsa_sha512
  2000/09/xmldsig#dsa-sha1: _2000_09_xmldsig_dsa_sha1
