name: authentikAPI
targets:
  authentikAPI:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [authentikAPI]
    info:
      path: ./Info.plist
      version: 2023.6.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
