name: authentikClient
targets:
  authentikClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: 2025.8.0-rc1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
