name: authentikClient
targets:
  authentikClient:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [authentikClient]
    info:
      path: ./Info.plist
      version: 2023.10.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
