//
// AuthenticatorStaticChallengeResponseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Pseudo class for static response 
public struct AuthenticatorStaticChallengeResponseRequest: Codable {
    public var component: String? = "ak-stage-authenticator-static"

    public init(component: String? = "ak-stage-authenticator-static") {
        self.component = component
    }
}
