//
// AutoSubmitChallengeResponseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Pseudo class for autosubmit response 
public struct AutoSubmitChallengeResponseRequest: Codable {
    public var component: String? = "ak-stage-autosubmit"

    public init(component: String? = "ak-stage-autosubmit") {
        self.component = component
    }
}
