//
// BlueprintInstance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Info about a single blueprint instance file 
public struct BlueprintInstance: Codable {
    public var pk: UUID
    public var name: String
    public var path: String? = ""
    public var context: [String: Any]?
    public var lastApplied: Date
    public var lastAppliedHash: String
    public var status: BlueprintInstanceStatusEnum
    public var enabled: Bool?
    public var managedModels: [String]
    public var metadata: [String: Any]
    public var content: String?

    public init(pk: UUID, name: String, path: String? = "", context: [String: Any]? = nil, lastApplied: Date, lastAppliedHash: String, status: BlueprintInstanceStatusEnum, enabled: Bool? = nil, managedModels: [String], metadata: [String: Any], content: String? = nil) {
        self.pk = pk
        self.name = name
        self.path = path
        self.context = context
        self.lastApplied = lastApplied
        self.lastAppliedHash = lastAppliedHash
        self.status = status
        self.enabled = enabled
        self.managedModels = managedModels
        self.metadata = metadata
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
        case name
        case path
        case context
        case lastApplied = "last_applied"
        case lastAppliedHash = "last_applied_hash"
        case status
        case enabled
        case managedModels = "managed_models"
        case metadata
        case content
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        pk = try container.decode(UUID.self, forKey: .pk)
        name = try container.decode(String.self, forKey: .name)
        path = try container.decodeIfPresent(String.self, forKey: .path)
        context = try container.decodeIfPresent([String: Any].self, forKey: .context)
        lastApplied = try container.decode(Date.self, forKey: .lastApplied)
        lastAppliedHash = try container.decode(String.self, forKey: .lastAppliedHash)
        status = try container.decode(BlueprintInstanceStatusEnum.self, forKey: .status)
        enabled = try container.decodeIfPresent(Bool.self, forKey: .enabled)
        managedModels = try container.decode([String].self, forKey: .managedModels)
        metadata = try container.decode([String: Any].self, forKey: .metadata)
        content = try container.decodeIfPresent(String.self, forKey: .content)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pk, forKey: .pk)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        if let context = context {
            try container.encodeIfPresent(try JSONSerialization.data(withJSONObject: context), forKey: .context)
        }
        try container.encode(lastApplied, forKey: .lastApplied)
        try container.encode(lastAppliedHash, forKey: .lastAppliedHash)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encode(managedModels, forKey: .managedModels)
        try container.encode(try JSONSerialization.data(withJSONObject: metadata), forKey: .metadata)
        try container.encodeIfPresent(content, forKey: .content)
    }
}
