//
// ContextualFlowInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Contextual flow information for a challenge 
public struct ContextualFlowInfo: Codable {
    public var title: String?
    public var background: String?
    public var cancelUrl: String
    public var layout: LayoutEnum

    public init(title: String? = nil, background: String? = nil, cancelUrl: String, layout: LayoutEnum) {
        self.title = title
        self.background = background
        self.cancelUrl = cancelUrl
        self.layout = layout
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case background
        case cancelUrl = "cancel_url"
        case layout
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        title = try container.decodeIfPresent(String.self, forKey: .title)
        background = try container.decodeIfPresent(String.self, forKey: .background)
        cancelUrl = try container.decode(String.self, forKey: .cancelUrl)
        layout = try container.decode(LayoutEnum.self, forKey: .layout)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(background, forKey: .background)
        try container.encode(cancelUrl, forKey: .cancelUrl)
        try container.encode(layout, forKey: .layout)
    }
}
