//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Event Serializer 
public struct Event: Codable {
    public var pk: UUID
    public var user: [String: AnyCodable]?
    public var action: EventActions
    public var app: String
    public var context: [String: AnyCodable]?
    public var clientIp: String?
    public var created: Date
    public var expires: Date?
    public var tenant: [String: AnyCodable]?

    public init(pk: UUID, user: [String: AnyCodable]? = nil, action: EventActions, app: String, context: [String: AnyCodable]? = nil, clientIp: String? = nil, created: Date, expires: Date? = nil, tenant: [String: AnyCodable]? = nil) {
        self.pk = pk
        self.user = user
        self.action = action
        self.app = app
        self.context = context
        self.clientIp = clientIp
        self.created = created
        self.expires = expires
        self.tenant = tenant
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
        case user
        case action
        case app
        case context
        case clientIp = "client_ip"
        case created
        case expires
        case tenant
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        pk = try container.decode(UUID.self, forKey: .pk)
        user = try container.decodeIfPresent([String: AnyCodable].self, forKey: .user)
        action = try container.decode(EventActions.self, forKey: .action)
        app = try container.decode(String.self, forKey: .app)
        context = try container.decodeIfPresent([String: AnyCodable].self, forKey: .context)
        clientIp = try container.decodeIfPresent(String.self, forKey: .clientIp)
        created = try container.decode(Date.self, forKey: .created)
        expires = try container.decodeIfPresent(Date.self, forKey: .expires)
        tenant = try container.decodeIfPresent([String: AnyCodable].self, forKey: .tenant)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pk, forKey: .pk)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encode(action, forKey: .action)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(clientIp, forKey: .clientIp)
        try container.encode(created, forKey: .created)
        try container.encodeIfPresent(expires, forKey: .expires)
        try container.encodeIfPresent(tenant, forKey: .tenant)
    }
}
