//
// IntentEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// * &#x60;verification&#x60; - Intent Verification * &#x60;api&#x60; - Intent Api * &#x60;recovery&#x60; - Intent Recovery * &#x60;app_password&#x60; - Intent App Password 
public enum IntentEnum: String, Codable, CaseIterable {
    case verification = "verification"
    case api = "api"
    case recovery = "recovery"
    case appPassword = "app_password"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
