//
// InvalidResponseActionEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// * &#x60;retry&#x60; - Retry * &#x60;restart&#x60; - Restart * &#x60;restart_with_context&#x60; - Restart With Context 
public enum InvalidResponseActionEnum: String, Codable, CaseIterable {
    case retry = "retry"
    case restart = "restart"
    case restartWithContext = "restart_with_context"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
