//
// Metadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Serializer for blueprint metadata 
public struct Metadata: Codable {
    public var name: String
    public var labels: [String: AnyCodable]

    public init(name: String, labels: [String: AnyCodable]) {
        self.name = name
        self.labels = labels
    }
}
