//
// NameIdPolicyEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// * &#x60;urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress&#x60; - Email * &#x60;urn:oasis:names:tc:SAML:2.0:nameid-format:persistent&#x60; - Persistent * &#x60;urn:oasis:names:tc:SAML:2.0:nameid-format:X509SubjectName&#x60; - X509 * &#x60;urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName&#x60; - Windows * &#x60;urn:oasis:names:tc:SAML:2.0:nameid-format:transient&#x60; - Transient 
public enum NameIdPolicyEnum: String, Codable, CaseIterable {
    case _1_1_nameid_format_emailAddress = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
    case _2_0_nameid_format_persistent = "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent"
    case _2_0_nameid_format_X509SubjectName = "urn:oasis:names:tc:SAML:2.0:nameid-format:X509SubjectName"
    case _2_0_nameid_format_WindowsDomainQualifiedName = "urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName"
    case _2_0_nameid_format_transient = "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
