//
// PaginatedAuthenticatorSMSStageList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedAuthenticatorSMSStageList: Codable {
    public var pagination: Pagination
    public var results: [AuthenticatorSMSStage]

    public init(pagination: Pagination, results: [AuthenticatorSMSStage]) {
        self.pagination = pagination
        self.results = results
    }
}
