//
// PaginatedUserLoginStageList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedUserLoginStageList: Codable {
    public var pagination: Pagination
    public var results: [UserLoginStage]

    public init(pagination: Pagination, results: [UserLoginStage]) {
        self.pagination = pagination
        self.results = results
    }
}
