//
// PaginatedAuthenticatorValidateStageList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedAuthenticatorValidateStageList: Codable {
    public var pagination: Pagination
    public var results: [AuthenticatorValidateStage]

    public init(pagination: Pagination, results: [AuthenticatorValidateStage]) {
        self.pagination = pagination
        self.results = results
    }
}
