//
// PaginatedAuthenticatorDuoStageList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedAuthenticatorDuoStageList: Codable {
    public var pagination: Pagination
    public var results: [AuthenticatorDuoStage]

    public init(pagination: Pagination, results: [AuthenticatorDuoStage]) {
        self.pagination = pagination
        self.results = results
    }
}
