//
// PaginatedExpressionPolicyList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedExpressionPolicyList: Codable {
    public var pagination: Pagination
    public var results: [ExpressionPolicy]

    public init(pagination: Pagination, results: [ExpressionPolicy]) {
        self.pagination = pagination
        self.results = results
    }
}
