//
// PaginatedInvitationList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedInvitationList: Codable {
    public var pagination: Pagination
    public var results: [Invitation]

    public init(pagination: Pagination, results: [Invitation]) {
        self.pagination = pagination
        self.results = results
    }
}
