//
// PaginatedUserDeleteStageList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedUserDeleteStageList: Codable {
    public var pagination: Pagination
    public var results: [UserDeleteStage]

    public init(pagination: Pagination, results: [UserDeleteStage]) {
        self.pagination = pagination
        self.results = results
    }
}
