//
// PaginatedDummyPolicyList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaginatedDummyPolicyList: Codable {
    public var pagination: Pagination
    public var results: [DummyPolicy]

    public init(pagination: Pagination, results: [DummyPolicy]) {
        self.pagination = pagination
        self.results = results
    }
}
