//
// PatchedUserWriteStageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// UserWriteStage Serializer 
public struct PatchedUserWriteStageRequest: Codable {
    public var name: String?
    public var flowSet: [FlowSetRequest]?
    public var userCreationMode: UserCreationModeEnum?
    /// When set, newly created users are inactive and cannot login.
    public var createUsersAsInactive: Bool?
    /// Optionally add newly created users to this group.
    public var createUsersGroup: UUID?
    public var userType: UserTypeEnum?
    public var userPathTemplate: String?

    public init(name: String? = nil, flowSet: [FlowSetRequest]? = nil, userCreationMode: UserCreationModeEnum? = nil, createUsersAsInactive: Bool? = nil, createUsersGroup: UUID? = nil, userType: UserTypeEnum? = nil, userPathTemplate: String? = nil) {
        self.name = name
        self.flowSet = flowSet
        self.userCreationMode = userCreationMode
        self.createUsersAsInactive = createUsersAsInactive
        self.createUsersGroup = createUsersGroup
        self.userType = userType
        self.userPathTemplate = userPathTemplate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case flowSet = "flow_set"
        case userCreationMode = "user_creation_mode"
        case createUsersAsInactive = "create_users_as_inactive"
        case createUsersGroup = "create_users_group"
        case userType = "user_type"
        case userPathTemplate = "user_path_template"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        name = try container.decodeIfPresent(String.self, forKey: .name)
        flowSet = try container.decodeIfPresent([FlowSetRequest].self, forKey: .flowSet)
        userCreationMode = try container.decodeIfPresent(UserCreationModeEnum.self, forKey: .userCreationMode)
        createUsersAsInactive = try container.decodeIfPresent(Bool.self, forKey: .createUsersAsInactive)
        createUsersGroup = try container.decodeIfPresent(UUID.self, forKey: .createUsersGroup)
        userType = try container.decodeIfPresent(UserTypeEnum.self, forKey: .userType)
        userPathTemplate = try container.decodeIfPresent(String.self, forKey: .userPathTemplate)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(flowSet, forKey: .flowSet)
        try container.encodeIfPresent(userCreationMode, forKey: .userCreationMode)
        try container.encodeIfPresent(createUsersAsInactive, forKey: .createUsersAsInactive)
        try container.encodeIfPresent(createUsersGroup, forKey: .createUsersGroup)
        try container.encodeIfPresent(userType, forKey: .userType)
        try container.encodeIfPresent(userPathTemplate, forKey: .userPathTemplate)
    }
}
