//
// PatchedNotificationWebhookMappingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// NotificationWebhookMapping Serializer 
public struct PatchedNotificationWebhookMappingRequest: Codable {
    public var name: String?
    public var expression: String?

    public init(name: String? = nil, expression: String? = nil) {
        self.name = name
        self.expression = expression
    }
}
