//
// PatchedSMSDeviceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Serializer for sms authenticator devices 
public struct PatchedSMSDeviceRequest: Codable {
    public var pk: String?
    public var name: String?

    public init(pk: String? = nil, name: String? = nil) {
        self.pk = pk
        self.name = name
    }
}
