//
// PolicyEngineMode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// * &#x60;all&#x60; - all, all policies must pass * &#x60;any&#x60; - any, any policy must pass 
public enum PolicyEngineMode: String, Codable, CaseIterable {
    case all = "all"
    case any = "any"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
