//
// RoleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// Role serializer 
public struct RoleRequest: Codable {
    public var name: String

    public init(name: String) {
        self.name = name
    }
}
