//
// SAMLMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// SAML Provider Metadata serializer 
public struct SAMLMetadata: Codable {
    public var metadata: String
    public var downloadUrl: String

    public init(metadata: String, downloadUrl: String) {
        self.metadata = metadata
        self.downloadUrl = downloadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metadata
        case downloadUrl = "download_url"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        metadata = try container.decode(String.self, forKey: .metadata)
        downloadUrl = try container.decode(String.self, forKey: .downloadUrl)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(downloadUrl, forKey: .downloadUrl)
    }
}
