//
// SAMLProvider.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// SAMLProvider Serializer 
public struct SAMLProvider: Codable {
    public var pk: Int
    public var name: String
    /// Flow used for authentication when the associated application is accessed by an un-authenticated user.
    public var authenticationFlow: UUID?
    /// Flow used when authorizing this provider.
    public var authorizationFlow: UUID
    public var propertyMappings: [UUID]?
    /// Get object component so that we know how to edit the object
    public var component: String
    /// Internal application name, used in URLs.
    public var assignedApplicationSlug: String
    /// Application's display Name.
    public var assignedApplicationName: String
    /// Internal application name, used in URLs.
    public var assignedBackchannelApplicationSlug: String
    /// Application's display Name.
    public var assignedBackchannelApplicationName: String
    /// Return object's verbose_name
    public var verboseName: String
    /// Return object's plural verbose_name
    public var verboseNamePlural: String
    /// Return internal model name
    public var metaModelName: String
    public var acsUrl: String
    /// Value of the audience restriction field of the assertion. When left empty, no audience restriction will be added.
    public var audience: String?
    /// Also known as EntityID
    public var issuer: String?
    /// Assertion valid not before current time + this value (Format: hours=-1;minutes=-2;seconds=-3).
    public var assertionValidNotBefore: String?
    /// Assertion not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
    public var assertionValidNotOnOrAfter: String?
    /// Session not valid on or after current time + this value (Format: hours=1;minutes=2;seconds=3).
    public var sessionValidNotOnOrAfter: String?
    /// Configure how the NameID value will be created. When left empty, the NameIDPolicy of the incoming request will be considered
    public var nameIdMapping: UUID?
    public var digestAlgorithm: DigestAlgorithmEnum?
    public var signatureAlgorithm: SignatureAlgorithmEnum?
    /// Keypair used to sign outgoing Responses going to the Service Provider.
    public var signingKp: UUID?
    /// When selected, incoming assertion's Signatures will be validated against this certificate. To allow unsigned Requests, leave on default.
    public var verificationKp: UUID?
    public var spBinding: SpBindingEnum?
    /// Default relay_state value for IDP-initiated logins
    public var defaultRelayState: String?
    /// Get metadata download URL
    public var urlDownloadMetadata: String
    /// Get SSO Post URL
    public var urlSsoPost: String
    /// Get SSO Redirect URL
    public var urlSsoRedirect: String
    /// Get SSO IDP-Initiated URL
    public var urlSsoInit: String
    /// Get SLO POST URL
    public var urlSloPost: String
    /// Get SLO redirect URL
    public var urlSloRedirect: String

    public init(pk: Int, name: String, authenticationFlow: UUID? = nil, authorizationFlow: UUID, propertyMappings: [UUID]? = nil, component: String, assignedApplicationSlug: String, assignedApplicationName: String, assignedBackchannelApplicationSlug: String, assignedBackchannelApplicationName: String, verboseName: String, verboseNamePlural: String, metaModelName: String, acsUrl: String, audience: String? = nil, issuer: String? = nil, assertionValidNotBefore: String? = nil, assertionValidNotOnOrAfter: String? = nil, sessionValidNotOnOrAfter: String? = nil, nameIdMapping: UUID? = nil, digestAlgorithm: DigestAlgorithmEnum? = nil, signatureAlgorithm: SignatureAlgorithmEnum? = nil, signingKp: UUID? = nil, verificationKp: UUID? = nil, spBinding: SpBindingEnum? = nil, defaultRelayState: String? = nil, urlDownloadMetadata: String, urlSsoPost: String, urlSsoRedirect: String, urlSsoInit: String, urlSloPost: String, urlSloRedirect: String) {
        self.pk = pk
        self.name = name
        self.authenticationFlow = authenticationFlow
        self.authorizationFlow = authorizationFlow
        self.propertyMappings = propertyMappings
        self.component = component
        self.assignedApplicationSlug = assignedApplicationSlug
        self.assignedApplicationName = assignedApplicationName
        self.assignedBackchannelApplicationSlug = assignedBackchannelApplicationSlug
        self.assignedBackchannelApplicationName = assignedBackchannelApplicationName
        self.verboseName = verboseName
        self.verboseNamePlural = verboseNamePlural
        self.metaModelName = metaModelName
        self.acsUrl = acsUrl
        self.audience = audience
        self.issuer = issuer
        self.assertionValidNotBefore = assertionValidNotBefore
        self.assertionValidNotOnOrAfter = assertionValidNotOnOrAfter
        self.sessionValidNotOnOrAfter = sessionValidNotOnOrAfter
        self.nameIdMapping = nameIdMapping
        self.digestAlgorithm = digestAlgorithm
        self.signatureAlgorithm = signatureAlgorithm
        self.signingKp = signingKp
        self.verificationKp = verificationKp
        self.spBinding = spBinding
        self.defaultRelayState = defaultRelayState
        self.urlDownloadMetadata = urlDownloadMetadata
        self.urlSsoPost = urlSsoPost
        self.urlSsoRedirect = urlSsoRedirect
        self.urlSsoInit = urlSsoInit
        self.urlSloPost = urlSloPost
        self.urlSloRedirect = urlSloRedirect
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
        case name
        case authenticationFlow = "authentication_flow"
        case authorizationFlow = "authorization_flow"
        case propertyMappings = "property_mappings"
        case component
        case assignedApplicationSlug = "assigned_application_slug"
        case assignedApplicationName = "assigned_application_name"
        case assignedBackchannelApplicationSlug = "assigned_backchannel_application_slug"
        case assignedBackchannelApplicationName = "assigned_backchannel_application_name"
        case verboseName = "verbose_name"
        case verboseNamePlural = "verbose_name_plural"
        case metaModelName = "meta_model_name"
        case acsUrl = "acs_url"
        case audience
        case issuer
        case assertionValidNotBefore = "assertion_valid_not_before"
        case assertionValidNotOnOrAfter = "assertion_valid_not_on_or_after"
        case sessionValidNotOnOrAfter = "session_valid_not_on_or_after"
        case nameIdMapping = "name_id_mapping"
        case digestAlgorithm = "digest_algorithm"
        case signatureAlgorithm = "signature_algorithm"
        case signingKp = "signing_kp"
        case verificationKp = "verification_kp"
        case spBinding = "sp_binding"
        case defaultRelayState = "default_relay_state"
        case urlDownloadMetadata = "url_download_metadata"
        case urlSsoPost = "url_sso_post"
        case urlSsoRedirect = "url_sso_redirect"
        case urlSsoInit = "url_sso_init"
        case urlSloPost = "url_slo_post"
        case urlSloRedirect = "url_slo_redirect"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        pk = try container.decode(Int.self, forKey: .pk)
        name = try container.decode(String.self, forKey: .name)
        authenticationFlow = try container.decodeIfPresent(UUID.self, forKey: .authenticationFlow)
        authorizationFlow = try container.decode(UUID.self, forKey: .authorizationFlow)
        propertyMappings = try container.decodeIfPresent([UUID].self, forKey: .propertyMappings)
        component = try container.decode(String.self, forKey: .component)
        assignedApplicationSlug = try container.decode(String.self, forKey: .assignedApplicationSlug)
        assignedApplicationName = try container.decode(String.self, forKey: .assignedApplicationName)
        assignedBackchannelApplicationSlug = try container.decode(String.self, forKey: .assignedBackchannelApplicationSlug)
        assignedBackchannelApplicationName = try container.decode(String.self, forKey: .assignedBackchannelApplicationName)
        verboseName = try container.decode(String.self, forKey: .verboseName)
        verboseNamePlural = try container.decode(String.self, forKey: .verboseNamePlural)
        metaModelName = try container.decode(String.self, forKey: .metaModelName)
        acsUrl = try container.decode(String.self, forKey: .acsUrl)
        audience = try container.decodeIfPresent(String.self, forKey: .audience)
        issuer = try container.decodeIfPresent(String.self, forKey: .issuer)
        assertionValidNotBefore = try container.decodeIfPresent(String.self, forKey: .assertionValidNotBefore)
        assertionValidNotOnOrAfter = try container.decodeIfPresent(String.self, forKey: .assertionValidNotOnOrAfter)
        sessionValidNotOnOrAfter = try container.decodeIfPresent(String.self, forKey: .sessionValidNotOnOrAfter)
        nameIdMapping = try container.decodeIfPresent(UUID.self, forKey: .nameIdMapping)
        digestAlgorithm = try container.decodeIfPresent(DigestAlgorithmEnum.self, forKey: .digestAlgorithm)
        signatureAlgorithm = try container.decodeIfPresent(SignatureAlgorithmEnum.self, forKey: .signatureAlgorithm)
        signingKp = try container.decodeIfPresent(UUID.self, forKey: .signingKp)
        verificationKp = try container.decodeIfPresent(UUID.self, forKey: .verificationKp)
        spBinding = try container.decodeIfPresent(SpBindingEnum.self, forKey: .spBinding)
        defaultRelayState = try container.decodeIfPresent(String.self, forKey: .defaultRelayState)
        urlDownloadMetadata = try container.decode(String.self, forKey: .urlDownloadMetadata)
        urlSsoPost = try container.decode(String.self, forKey: .urlSsoPost)
        urlSsoRedirect = try container.decode(String.self, forKey: .urlSsoRedirect)
        urlSsoInit = try container.decode(String.self, forKey: .urlSsoInit)
        urlSloPost = try container.decode(String.self, forKey: .urlSloPost)
        urlSloRedirect = try container.decode(String.self, forKey: .urlSloRedirect)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pk, forKey: .pk)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(authenticationFlow, forKey: .authenticationFlow)
        try container.encode(authorizationFlow, forKey: .authorizationFlow)
        try container.encodeIfPresent(propertyMappings, forKey: .propertyMappings)
        try container.encode(component, forKey: .component)
        try container.encode(assignedApplicationSlug, forKey: .assignedApplicationSlug)
        try container.encode(assignedApplicationName, forKey: .assignedApplicationName)
        try container.encode(assignedBackchannelApplicationSlug, forKey: .assignedBackchannelApplicationSlug)
        try container.encode(assignedBackchannelApplicationName, forKey: .assignedBackchannelApplicationName)
        try container.encode(verboseName, forKey: .verboseName)
        try container.encode(verboseNamePlural, forKey: .verboseNamePlural)
        try container.encode(metaModelName, forKey: .metaModelName)
        try container.encode(acsUrl, forKey: .acsUrl)
        try container.encodeIfPresent(audience, forKey: .audience)
        try container.encodeIfPresent(issuer, forKey: .issuer)
        try container.encodeIfPresent(assertionValidNotBefore, forKey: .assertionValidNotBefore)
        try container.encodeIfPresent(assertionValidNotOnOrAfter, forKey: .assertionValidNotOnOrAfter)
        try container.encodeIfPresent(sessionValidNotOnOrAfter, forKey: .sessionValidNotOnOrAfter)
        try container.encodeIfPresent(nameIdMapping, forKey: .nameIdMapping)
        try container.encodeIfPresent(digestAlgorithm, forKey: .digestAlgorithm)
        try container.encodeIfPresent(signatureAlgorithm, forKey: .signatureAlgorithm)
        try container.encodeIfPresent(signingKp, forKey: .signingKp)
        try container.encodeIfPresent(verificationKp, forKey: .verificationKp)
        try container.encodeIfPresent(spBinding, forKey: .spBinding)
        try container.encodeIfPresent(defaultRelayState, forKey: .defaultRelayState)
        try container.encode(urlDownloadMetadata, forKey: .urlDownloadMetadata)
        try container.encode(urlSsoPost, forKey: .urlSsoPost)
        try container.encode(urlSsoRedirect, forKey: .urlSsoRedirect)
        try container.encode(urlSsoInit, forKey: .urlSsoInit)
        try container.encode(urlSloPost, forKey: .urlSloPost)
        try container.encode(urlSloRedirect, forKey: .urlSloRedirect)
    }
}
