//
// ServiceConnectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/// ServiceConnection Serializer 
public struct ServiceConnectionRequest: Codable {
    public var name: String
    /// If enabled, use the local connection. Required Docker socket/Kubernetes Integration
    public var local: Bool?

    public init(name: String, local: Bool? = nil) {
        self.name = name
        self.local = local
    }
}
