//
// Workers.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Workers: Codable {
    public var count: Int

    public init(count: Int) {
        self.count = count
    }
}
