//
// FlowsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class FlowsAPI {

    /**

     - parameter flowStageBindingRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowStageBinding
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsCreate(flowStageBindingRequest: FlowStageBindingRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowStageBinding {
        return try await flowsBindingsCreateWithRequestBuilder(flowStageBindingRequest: flowStageBindingRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /flows/bindings/
     - FlowStageBinding Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter flowStageBindingRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowStageBinding> 
     */
    open class func flowsBindingsCreateWithRequestBuilder(flowStageBindingRequest: FlowStageBindingRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowStageBinding> {
        let localVariablePath = "/flows/bindings/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: flowStageBindingRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowStageBinding>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsDestroy(fsbUuid: UUID, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await flowsBindingsDestroyWithRequestBuilder(fsbUuid: fsbUuid, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /flows/bindings/{fsb_uuid}/
     - FlowStageBinding Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func flowsBindingsDestroyWithRequestBuilder(fsbUuid: UUID, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/flows/bindings/{fsb_uuid}/"
        let fsbUuidPreEscape = "\(APIHelper.mapValueToPathItem(fsbUuid))"
        let fsbUuidPostEscape = fsbUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fsb_uuid}", with: fsbUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter invalidResponseAction
     */
    public enum InvalidResponseAction_flowsBindingsList: String, Sendable, CaseIterable {
        case restart = "restart"
        case restartWithContext = "restart_with_context"
        case retry = "retry"
    }

    /**
     * enum for parameter policyEngineMode
     */
    public enum PolicyEngineMode_flowsBindingsList: String, Sendable, CaseIterable {
        case all = "all"
        case any = "any"
    }

    /**

     - parameter evaluateOnPlan: (query)  (optional)
     - parameter fsbUuid: (query)  (optional)
     - parameter invalidResponseAction: (query) Configure how the flow executor should handle an invalid response to a challenge. RETRY returns the error message and a similar challenge to the executor. RESTART restarts the flow from the beginning, and RESTART_WITH_CONTEXT restarts the flow while keeping the current context.   (optional)
     - parameter order: (query)  (optional)
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter pageSize: (query) Number of results to return per page. (optional)
     - parameter pbmUuid: (query)  (optional)
     - parameter policies: (query)  (optional)
     - parameter policyEngineMode: (query)  (optional)
     - parameter reEvaluatePolicies: (query)  (optional)
     - parameter search: (query) A search term. (optional)
     - parameter stage: (query)  (optional)
     - parameter target: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedFlowStageBindingList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsList(evaluateOnPlan: Bool? = nil, fsbUuid: UUID? = nil, invalidResponseAction: InvalidResponseAction_flowsBindingsList? = nil, order: Int? = nil, ordering: String? = nil, page: Int? = nil, pageSize: Int? = nil, pbmUuid: UUID? = nil, policies: [UUID]? = nil, policyEngineMode: PolicyEngineMode_flowsBindingsList? = nil, reEvaluatePolicies: Bool? = nil, search: String? = nil, stage: UUID? = nil, target: UUID? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedFlowStageBindingList {
        return try await flowsBindingsListWithRequestBuilder(evaluateOnPlan: evaluateOnPlan, fsbUuid: fsbUuid, invalidResponseAction: invalidResponseAction, order: order, ordering: ordering, page: page, pageSize: pageSize, pbmUuid: pbmUuid, policies: policies, policyEngineMode: policyEngineMode, reEvaluatePolicies: reEvaluatePolicies, search: search, stage: stage, target: target, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/bindings/
     - FlowStageBinding Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter evaluateOnPlan: (query)  (optional)
     - parameter fsbUuid: (query)  (optional)
     - parameter invalidResponseAction: (query) Configure how the flow executor should handle an invalid response to a challenge. RETRY returns the error message and a similar challenge to the executor. RESTART restarts the flow from the beginning, and RESTART_WITH_CONTEXT restarts the flow while keeping the current context.   (optional)
     - parameter order: (query)  (optional)
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter pageSize: (query) Number of results to return per page. (optional)
     - parameter pbmUuid: (query)  (optional)
     - parameter policies: (query)  (optional)
     - parameter policyEngineMode: (query)  (optional)
     - parameter reEvaluatePolicies: (query)  (optional)
     - parameter search: (query) A search term. (optional)
     - parameter stage: (query)  (optional)
     - parameter target: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedFlowStageBindingList> 
     */
    open class func flowsBindingsListWithRequestBuilder(evaluateOnPlan: Bool? = nil, fsbUuid: UUID? = nil, invalidResponseAction: InvalidResponseAction_flowsBindingsList? = nil, order: Int? = nil, ordering: String? = nil, page: Int? = nil, pageSize: Int? = nil, pbmUuid: UUID? = nil, policies: [UUID]? = nil, policyEngineMode: PolicyEngineMode_flowsBindingsList? = nil, reEvaluatePolicies: Bool? = nil, search: String? = nil, stage: UUID? = nil, target: UUID? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<PaginatedFlowStageBindingList> {
        let localVariablePath = "/flows/bindings/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "evaluate_on_plan": (wrappedValue: evaluateOnPlan?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "fsb_uuid": (wrappedValue: fsbUuid?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "invalid_response_action": (wrappedValue: invalidResponseAction?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "order": (wrappedValue: order?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "ordering": (wrappedValue: ordering?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pbm_uuid": (wrappedValue: pbmUuid?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "policies": (wrappedValue: policies?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "policy_engine_mode": (wrappedValue: policyEngineMode?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "re_evaluate_policies": (wrappedValue: reEvaluatePolicies?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "search": (wrappedValue: search?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "stage": (wrappedValue: stage?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "target": (wrappedValue: target?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedFlowStageBindingList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter patchedFlowStageBindingRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowStageBinding
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsPartialUpdate(fsbUuid: UUID, patchedFlowStageBindingRequest: PatchedFlowStageBindingRequest? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowStageBinding {
        return try await flowsBindingsPartialUpdateWithRequestBuilder(fsbUuid: fsbUuid, patchedFlowStageBindingRequest: patchedFlowStageBindingRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PATCH /flows/bindings/{fsb_uuid}/
     - FlowStageBinding Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter patchedFlowStageBindingRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowStageBinding> 
     */
    open class func flowsBindingsPartialUpdateWithRequestBuilder(fsbUuid: UUID, patchedFlowStageBindingRequest: PatchedFlowStageBindingRequest? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowStageBinding> {
        var localVariablePath = "/flows/bindings/{fsb_uuid}/"
        let fsbUuidPreEscape = "\(APIHelper.mapValueToPathItem(fsbUuid))"
        let fsbUuidPostEscape = fsbUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fsb_uuid}", with: fsbUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: patchedFlowStageBindingRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowStageBinding>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowStageBinding
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsRetrieve(fsbUuid: UUID, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowStageBinding {
        return try await flowsBindingsRetrieveWithRequestBuilder(fsbUuid: fsbUuid, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/bindings/{fsb_uuid}/
     - FlowStageBinding Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowStageBinding> 
     */
    open class func flowsBindingsRetrieveWithRequestBuilder(fsbUuid: UUID, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowStageBinding> {
        var localVariablePath = "/flows/bindings/{fsb_uuid}/"
        let fsbUuidPreEscape = "\(APIHelper.mapValueToPathItem(fsbUuid))"
        let fsbUuidPostEscape = fsbUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fsb_uuid}", with: fsbUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowStageBinding>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter flowStageBindingRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowStageBinding
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsUpdate(fsbUuid: UUID, flowStageBindingRequest: FlowStageBindingRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowStageBinding {
        return try await flowsBindingsUpdateWithRequestBuilder(fsbUuid: fsbUuid, flowStageBindingRequest: flowStageBindingRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PUT /flows/bindings/{fsb_uuid}/
     - FlowStageBinding Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter flowStageBindingRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowStageBinding> 
     */
    open class func flowsBindingsUpdateWithRequestBuilder(fsbUuid: UUID, flowStageBindingRequest: FlowStageBindingRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowStageBinding> {
        var localVariablePath = "/flows/bindings/{fsb_uuid}/"
        let fsbUuidPreEscape = "\(APIHelper.mapValueToPathItem(fsbUuid))"
        let fsbUuidPostEscape = fsbUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fsb_uuid}", with: fsbUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: flowStageBindingRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowStageBinding>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [UsedBy]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsBindingsUsedByList(fsbUuid: UUID, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> [UsedBy] {
        return try await flowsBindingsUsedByListWithRequestBuilder(fsbUuid: fsbUuid, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/bindings/{fsb_uuid}/used_by/
     - Get a list of all objects that use this object
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter fsbUuid: (path) A UUID string identifying this Flow Stage Binding. 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[UsedBy]> 
     */
    open class func flowsBindingsUsedByListWithRequestBuilder(fsbUuid: UUID, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<[UsedBy]> {
        var localVariablePath = "/flows/bindings/{fsb_uuid}/used_by/"
        let fsbUuidPreEscape = "\(APIHelper.mapValueToPathItem(fsbUuid))"
        let fsbUuidPostEscape = fsbUuidPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{fsb_uuid}", with: fsbUuidPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UsedBy]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter flowSlug: (path)  
     - parameter query: (query) Querystring as received 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ChallengeTypes
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsExecutorGet(flowSlug: String, query: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> ChallengeTypes {
        return try await flowsExecutorGetWithRequestBuilder(flowSlug: flowSlug, query: query, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/executor/{flow_slug}/
     - Get the next pending challenge from the currently active flow.
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter flowSlug: (path)  
     - parameter query: (query) Querystring as received 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ChallengeTypes> 
     */
    open class func flowsExecutorGetWithRequestBuilder(flowSlug: String, query: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<ChallengeTypes> {
        var localVariablePath = "/flows/executor/{flow_slug}/"
        let flowSlugPreEscape = "\(APIHelper.mapValueToPathItem(flowSlug))"
        let flowSlugPostEscape = flowSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flow_slug}", with: flowSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ChallengeTypes>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter flowSlug: (path)  
     - parameter query: (query) Querystring as received 
     - parameter flowChallengeResponseRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ChallengeTypes
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsExecutorSolve(flowSlug: String, query: String, flowChallengeResponseRequest: FlowChallengeResponseRequest? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> ChallengeTypes {
        return try await flowsExecutorSolveWithRequestBuilder(flowSlug: flowSlug, query: query, flowChallengeResponseRequest: flowChallengeResponseRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /flows/executor/{flow_slug}/
     - Solve the previously retrieved challenge and advanced to the next stage.
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter flowSlug: (path)  
     - parameter query: (query) Querystring as received 
     - parameter flowChallengeResponseRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ChallengeTypes> 
     */
    open class func flowsExecutorSolveWithRequestBuilder(flowSlug: String, query: String, flowChallengeResponseRequest: FlowChallengeResponseRequest? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<ChallengeTypes> {
        var localVariablePath = "/flows/executor/{flow_slug}/"
        let flowSlugPreEscape = "\(APIHelper.mapValueToPathItem(flowSlug))"
        let flowSlugPostEscape = flowSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flow_slug}", with: flowSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: flowChallengeResponseRequest, codableHelper: apiConfiguration.codableHelper)

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "query": (wrappedValue: query.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ChallengeTypes>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter flowSlug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowInspection
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInspectorGet(flowSlug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowInspection {
        return try await flowsInspectorGetWithRequestBuilder(flowSlug: flowSlug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/inspector/{flow_slug}/
     - Get current flow state and record it
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter flowSlug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowInspection> 
     */
    open class func flowsInspectorGetWithRequestBuilder(flowSlug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowInspection> {
        var localVariablePath = "/flows/inspector/{flow_slug}/"
        let flowSlugPreEscape = "\(APIHelper.mapValueToPathItem(flowSlug))"
        let flowSlugPostEscape = flowSlugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{flow_slug}", with: flowSlugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowInspection>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesCacheClearCreate(apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await flowsInstancesCacheClearCreateWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /flows/instances/cache_clear/
     - Clear flow cache
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func flowsInstancesCacheClearCreateWithRequestBuilder(apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        let localVariablePath = "/flows/instances/cache_clear/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: Cache
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesCacheInfoRetrieve(apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> Cache {
        return try await flowsInstancesCacheInfoRetrieveWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/cache_info/
     - Info about cached flows
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Cache> 
     */
    open class func flowsInstancesCacheInfoRetrieveWithRequestBuilder(apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Cache> {
        let localVariablePath = "/flows/instances/cache_info/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Cache>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter flowRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Flow
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesCreate(flowRequest: FlowRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> Flow {
        return try await flowsInstancesCreateWithRequestBuilder(flowRequest: flowRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /flows/instances/
     - Flow Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter flowRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Flow> 
     */
    open class func flowsInstancesCreateWithRequestBuilder(flowRequest: FlowRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Flow> {
        let localVariablePath = "/flows/instances/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: flowRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Flow>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesDestroy(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await flowsInstancesDestroyWithRequestBuilder(slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /flows/instances/{slug}/
     - Flow Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func flowsInstancesDestroyWithRequestBuilder(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/flows/instances/{slug}/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowDiagram
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesDiagramRetrieve(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowDiagram {
        return try await flowsInstancesDiagramRetrieveWithRequestBuilder(slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/{slug}/diagram/
     - Return diagram for flow with slug `slug`, in the format used by flowchart.js
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowDiagram> 
     */
    open class func flowsInstancesDiagramRetrieveWithRequestBuilder(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowDiagram> {
        var localVariablePath = "/flows/instances/{slug}/diagram/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowDiagram>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Link
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesExecuteRetrieve(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> Link {
        return try await flowsInstancesExecuteRetrieveWithRequestBuilder(slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/{slug}/execute/
     - Execute flow for current user
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Link> 
     */
    open class func flowsInstancesExecuteRetrieveWithRequestBuilder(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Link> {
        var localVariablePath = "/flows/instances/{slug}/execute/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Link>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: URL
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesExportRetrieve(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> URL {
        return try await flowsInstancesExportRetrieveWithRequestBuilder(slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/{slug}/export/
     - Export flow to .yaml file
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<URL> 
     */
    open class func flowsInstancesExportRetrieveWithRequestBuilder(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<URL> {
        var localVariablePath = "/flows/instances/{slug}/export/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<URL>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter file: (form)  (optional)
     - parameter clear: (form)  (optional, default to false)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: FlowImportResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesImportCreate(file: URL? = nil, clear: Bool? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> FlowImportResult {
        return try await flowsInstancesImportCreateWithRequestBuilder(file: file, clear: clear, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /flows/instances/import/
     - Import flow from .yaml file
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter file: (form)  (optional)
     - parameter clear: (form)  (optional, default to false)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<FlowImportResult> 
     */
    open class func flowsInstancesImportCreateWithRequestBuilder(file: URL? = nil, clear: Bool? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<FlowImportResult> {
        let localVariablePath = "/flows/instances/import/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableFormParams: [String: (any Sendable)?] = [
            "file": file?.asParameter(codableHelper: apiConfiguration.codableHelper),
            "clear": clear?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<FlowImportResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     * enum for parameter deniedAction
     */
    public enum DeniedAction_flowsInstancesList: String, Sendable, CaseIterable {
        case _continue = "continue"
        case message = "message"
        case messageContinue = "message_continue"
    }

    /**
     * enum for parameter designation
     */
    public enum Designation_flowsInstancesList: String, Sendable, CaseIterable {
        case authentication = "authentication"
        case authorization = "authorization"
        case enrollment = "enrollment"
        case invalidation = "invalidation"
        case recovery = "recovery"
        case stageConfiguration = "stage_configuration"
        case unenrollment = "unenrollment"
    }

    /**

     - parameter deniedAction: (query) Configure what should happen when a flow denies access to a user.   (optional)
     - parameter designation: (query) Decides what this Flow is used for. For example, the Authentication flow is redirect to when an un-authenticated user visits authentik.   (optional)
     - parameter flowUuid: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter pageSize: (query) Number of results to return per page. (optional)
     - parameter search: (query) A search term. (optional)
     - parameter slug: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PaginatedFlowList
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesList(deniedAction: DeniedAction_flowsInstancesList? = nil, designation: Designation_flowsInstancesList? = nil, flowUuid: UUID? = nil, name: String? = nil, ordering: String? = nil, page: Int? = nil, pageSize: Int? = nil, search: String? = nil, slug: String? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> PaginatedFlowList {
        return try await flowsInstancesListWithRequestBuilder(deniedAction: deniedAction, designation: designation, flowUuid: flowUuid, name: name, ordering: ordering, page: page, pageSize: pageSize, search: search, slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/
     - Flow Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter deniedAction: (query) Configure what should happen when a flow denies access to a user.   (optional)
     - parameter designation: (query) Decides what this Flow is used for. For example, the Authentication flow is redirect to when an un-authenticated user visits authentik.   (optional)
     - parameter flowUuid: (query)  (optional)
     - parameter name: (query)  (optional)
     - parameter ordering: (query) Which field to use when ordering the results. (optional)
     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter pageSize: (query) Number of results to return per page. (optional)
     - parameter search: (query) A search term. (optional)
     - parameter slug: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PaginatedFlowList> 
     */
    open class func flowsInstancesListWithRequestBuilder(deniedAction: DeniedAction_flowsInstancesList? = nil, designation: Designation_flowsInstancesList? = nil, flowUuid: UUID? = nil, name: String? = nil, ordering: String? = nil, page: Int? = nil, pageSize: Int? = nil, search: String? = nil, slug: String? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<PaginatedFlowList> {
        let localVariablePath = "/flows/instances/"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "denied_action": (wrappedValue: deniedAction?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "designation": (wrappedValue: designation?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "flow_uuid": (wrappedValue: flowUuid?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "name": (wrappedValue: name?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "ordering": (wrappedValue: ordering?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_size": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "search": (wrappedValue: search?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "slug": (wrappedValue: slug?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PaginatedFlowList>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter patchedFlowRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Flow
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesPartialUpdate(slug: String, patchedFlowRequest: PatchedFlowRequest? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> Flow {
        return try await flowsInstancesPartialUpdateWithRequestBuilder(slug: slug, patchedFlowRequest: patchedFlowRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PATCH /flows/instances/{slug}/
     - Flow Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter patchedFlowRequest: (body)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Flow> 
     */
    open class func flowsInstancesPartialUpdateWithRequestBuilder(slug: String, patchedFlowRequest: PatchedFlowRequest? = nil, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Flow> {
        var localVariablePath = "/flows/instances/{slug}/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: patchedFlowRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Flow>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Flow
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesRetrieve(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> Flow {
        return try await flowsInstancesRetrieveWithRequestBuilder(slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/{slug}/
     - Flow Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Flow> 
     */
    open class func flowsInstancesRetrieveWithRequestBuilder(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Flow> {
        var localVariablePath = "/flows/instances/{slug}/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Flow>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter flowRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Flow
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesUpdate(slug: String, flowRequest: FlowRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> Flow {
        return try await flowsInstancesUpdateWithRequestBuilder(slug: slug, flowRequest: flowRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PUT /flows/instances/{slug}/
     - Flow Viewset
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter flowRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Flow> 
     */
    open class func flowsInstancesUpdateWithRequestBuilder(slug: String, flowRequest: FlowRequest, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<Flow> {
        var localVariablePath = "/flows/instances/{slug}/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: flowRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Flow>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [UsedBy]
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func flowsInstancesUsedByList(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) async throws(ErrorResponse) -> [UsedBy] {
        return try await flowsInstancesUsedByListWithRequestBuilder(slug: slug, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /flows/instances/{slug}/used_by/
     - Get a list of all objects that use this object
     - Bearer Token:
       - type: http
       - name: authentik
     - parameter slug: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[UsedBy]> 
     */
    open class func flowsInstancesUsedByListWithRequestBuilder(slug: String, apiConfiguration: authentikClientAPIConfiguration = authentikClientAPIConfiguration.shared) -> RequestBuilder<[UsedBy]> {
        var localVariablePath = "/flows/instances/{slug}/used_by/"
        let slugPreEscape = "\(APIHelper.mapValueToPathItem(slug))"
        let slugPostEscape = slugPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{slug}", with: slugPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[UsedBy]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
