//
// ErrorDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Serializer for rest_framework&#39;s error messages */
public struct ErrorDetail: Codable, JSONEncodable, Hashable {

    public var string: String
    public var code: String

    public init(string: String, code: String) {
        self.string = string
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case string
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(string, forKey: .string)
        try container.encode(code, forKey: .code)
    }
}

