//
// ProviderEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;twilio&#x60; - Twilio * &#x60;generic&#x60; - Generic */
public enum ProviderEnum: String, Codable, CaseIterable, CaseIterableDefaultsLast {
    case twilio = "twilio"
    case generic = "generic"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
