//
// AgentTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Base serializer class which doesn&#39;t implement create/update methods */
public struct AgentTokenResponse: Sendable, Codable, ParameterConvertible, Hashable {

    public var token: String
    public var expiresIn: Int?

    public init(token: String, expiresIn: Int? = nil) {
        self.token = token
        self.expiresIn = expiresIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case expiresIn = "expires_in"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encodeIfPresent(expiresIn, forKey: .expiresIn)
    }
}

