//
// AgentConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Base serializer class which doesn&#39;t implement create/update methods */
public struct AgentConfig: Sendable, Codable, ParameterConvertible, Hashable {

    public var nssUidOffset: Int
    public var nssGidOffset: Int
    public var authenticationFlow: String
    public var authTerminateSessionOnExpiry: Bool
    public var refreshInterval: Int

    public init(nssUidOffset: Int, nssGidOffset: Int, authenticationFlow: String, authTerminateSessionOnExpiry: Bool, refreshInterval: Int) {
        self.nssUidOffset = nssUidOffset
        self.nssGidOffset = nssGidOffset
        self.authenticationFlow = authenticationFlow
        self.authTerminateSessionOnExpiry = authTerminateSessionOnExpiry
        self.refreshInterval = refreshInterval
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nssUidOffset = "nss_uid_offset"
        case nssGidOffset = "nss_gid_offset"
        case authenticationFlow = "authentication_flow"
        case authTerminateSessionOnExpiry = "auth_terminate_session_on_expiry"
        case refreshInterval = "refresh_interval"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nssUidOffset, forKey: .nssUidOffset)
        try container.encode(nssGidOffset, forKey: .nssGidOffset)
        try container.encode(authenticationFlow, forKey: .authenticationFlow)
        try container.encode(authTerminateSessionOnExpiry, forKey: .authTerminateSessionOnExpiry)
        try container.encode(refreshInterval, forKey: .refreshInterval)
    }
}

