//
// App.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Serialize Application info */
public struct App: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: String
    public var label: String

    public init(name: String, label: String) {
        self.name = name
        self.label = label
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case label
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(label, forKey: .label)
    }
}

