//
// ApplicationEntitlement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ApplicationEntitlement Serializer */
public struct ApplicationEntitlement: Sendable, Codable, ParameterConvertible, Hashable {

    public var pbmUuid: UUID
    public var name: String
    public var app: UUID
    public var attributes: [String: JSONValue]?

    public init(pbmUuid: UUID, name: String, app: UUID, attributes: [String: JSONValue]? = nil) {
        self.pbmUuid = pbmUuid
        self.name = name
        self.app = app
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pbmUuid = "pbm_uuid"
        case name
        case app
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pbmUuid, forKey: .pbmUuid)
        try container.encode(name, forKey: .name)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

