//
// AuthenticatedSessionAsn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Get ASN Data */
public struct AuthenticatedSessionAsn: Sendable, Codable, ParameterConvertible, Hashable {

    public var asn: Int
    public var asOrg: String?
    public var network: String?

    public init(asn: Int, asOrg: String?, network: String?) {
        self.asn = asn
        self.asOrg = asOrg
        self.network = network
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asn
        case asOrg = "as_org"
        case network
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(asn, forKey: .asn)
        try container.encode(asOrg, forKey: .asOrg)
        try container.encode(network, forKey: .network)
    }
}

