//
// AuthenticatorAttachmentEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum AuthenticatorAttachmentEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case platform = "platform"
    case crossPlatform = "cross-platform"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
