//
// AutoSubmitChallengeResponseRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Pseudo class for autosubmit response */
public struct AutoSubmitChallengeResponseRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let componentRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var component: String? = "ak-stage-autosubmit"

    public init(component: String? = "ak-stage-autosubmit") {
        self.component = component
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case component
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(component, forKey: .component)
    }
}

