//
// BlueprintInstanceStatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BlueprintInstanceStatusEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case successful = "successful"
    case warning = "warning"
    case error = "error"
    case orphaned = "orphaned"
    case unknown = "unknown"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
