//
// CertAttributeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum CertAttributeEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case subject = "subject"
    case commonName = "common_name"
    case email = "email"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
