//
// ConnectionTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ConnectionToken Serializer */
public struct ConnectionTokenRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var pk: UUID?
    public var provider: Int
    public var endpoint: UUID

    public init(pk: UUID? = nil, provider: Int, endpoint: UUID) {
        self.pk = pk
        self.provider = provider
        self.endpoint = endpoint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
        case provider
        case endpoint
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pk, forKey: .pk)
        try container.encode(provider, forKey: .provider)
        try container.encode(endpoint, forKey: .endpoint)
    }
}

