//
// DiskRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiskRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let mountpointRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var mountpoint: String
    public var label: String?
    public var capacityTotalBytes: Int64?
    public var capacityUsedBytes: Int64?
    public var encryptionEnabled: Bool? = false

    public init(name: String, mountpoint: String, label: String? = nil, capacityTotalBytes: Int64? = nil, capacityUsedBytes: Int64? = nil, encryptionEnabled: Bool? = false) {
        self.name = name
        self.mountpoint = mountpoint
        self.label = label
        self.capacityTotalBytes = capacityTotalBytes
        self.capacityUsedBytes = capacityUsedBytes
        self.encryptionEnabled = encryptionEnabled
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case mountpoint
        case label
        case capacityTotalBytes = "capacity_total_bytes"
        case capacityUsedBytes = "capacity_used_bytes"
        case encryptionEnabled = "encryption_enabled"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(mountpoint, forKey: .mountpoint)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(capacityTotalBytes, forKey: .capacityTotalBytes)
        try container.encodeIfPresent(capacityUsedBytes, forKey: .capacityUsedBytes)
        try container.encodeIfPresent(encryptionEnabled, forKey: .encryptionEnabled)
    }
}

