//
// DuoDeviceEnrollmentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DuoDeviceEnrollmentStatus: Sendable, Codable, ParameterConvertible, Hashable {

    public var duoResponse: DuoResponseEnum

    public init(duoResponse: DuoResponseEnum) {
        self.duoResponse = duoResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case duoResponse = "duo_response"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(duoResponse, forKey: .duoResponse)
    }
}

