//
// EndpointAuthModeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum EndpointAuthModeEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _static = "static"
    case prompt = "prompt"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
