//
// EventRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Event Serializer */
public struct EventRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let appRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public static let clientIpRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var user: [String: JSONValue]?
    public var action: EventActions
    public var app: String
    public var context: [String: JSONValue]?
    public var clientIp: String?
    public var expires: Date?
    public var brand: [String: JSONValue]?

    public init(user: [String: JSONValue]? = nil, action: EventActions, app: String, context: [String: JSONValue]? = nil, clientIp: String? = nil, expires: Date? = nil, brand: [String: JSONValue]? = nil) {
        self.user = user
        self.action = action
        self.app = app
        self.context = context
        self.clientIp = clientIp
        self.expires = expires
        self.brand = brand
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case action
        case app
        case context
        case clientIp = "client_ip"
        case expires
        case brand
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encode(action, forKey: .action)
        try container.encode(app, forKey: .app)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(clientIp, forKey: .clientIp)
        try container.encodeIfPresent(expires, forKey: .expires)
        try container.encodeIfPresent(brand, forKey: .brand)
    }
}

