//
// FlowImportResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Logs of an attempted flow import */
public struct FlowImportResult: Sendable, Codable, ParameterConvertible, Hashable {

    public var logs: [LogEvent]
    public var success: Bool

    public init(logs: [LogEvent], success: Bool) {
        self.logs = logs
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case logs
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(logs, forKey: .logs)
        try container.encode(success, forKey: .success)
    }
}

