//
// IdentificationStageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** IdentificationStage Serializer */
public struct IdentificationStageRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    /** Fields of the user object to match against. (Hold shift to select multiple options) */
    public var userFields: [UserFieldsEnum]?
    /** When set, shows a password field, instead of showing the password field as separate step. */
    public var passwordStage: UUID?
    /** When set, adds functionality exactly like a Captcha stage, but baked into the Identification stage. */
    public var captchaStage: UUID?
    /** When enabled, user fields are matched regardless of their casing. */
    public var caseInsensitiveMatching: Bool?
    /** When a valid username/email has been entered, and this option is enabled, the user's username and avatar will be shown. Otherwise, the text that the user entered will be shown */
    public var showMatchedUser: Bool?
    /** Optional enrollment flow, which is linked at the bottom of the page. */
    public var enrollmentFlow: UUID?
    /** Optional recovery flow, which is linked at the bottom of the page. */
    public var recoveryFlow: UUID?
    /** Optional passwordless flow, which is linked at the bottom of the page. */
    public var passwordlessFlow: UUID?
    /** Specify which sources should be shown. */
    public var sources: [UUID]?
    public var showSourceLabels: Bool?
    /** When enabled, the stage will succeed and continue even when incorrect user info is entered. */
    public var pretendUserExists: Bool?
    /** Show the user the 'Remember me on this device' toggle, allowing repeat users to skip straight to entering their password. */
    public var enableRememberMe: Bool?

    public init(name: String, userFields: [UserFieldsEnum]? = nil, passwordStage: UUID? = nil, captchaStage: UUID? = nil, caseInsensitiveMatching: Bool? = nil, showMatchedUser: Bool? = nil, enrollmentFlow: UUID? = nil, recoveryFlow: UUID? = nil, passwordlessFlow: UUID? = nil, sources: [UUID]? = nil, showSourceLabels: Bool? = nil, pretendUserExists: Bool? = nil, enableRememberMe: Bool? = nil) {
        self.name = name
        self.userFields = userFields
        self.passwordStage = passwordStage
        self.captchaStage = captchaStage
        self.caseInsensitiveMatching = caseInsensitiveMatching
        self.showMatchedUser = showMatchedUser
        self.enrollmentFlow = enrollmentFlow
        self.recoveryFlow = recoveryFlow
        self.passwordlessFlow = passwordlessFlow
        self.sources = sources
        self.showSourceLabels = showSourceLabels
        self.pretendUserExists = pretendUserExists
        self.enableRememberMe = enableRememberMe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case userFields = "user_fields"
        case passwordStage = "password_stage"
        case captchaStage = "captcha_stage"
        case caseInsensitiveMatching = "case_insensitive_matching"
        case showMatchedUser = "show_matched_user"
        case enrollmentFlow = "enrollment_flow"
        case recoveryFlow = "recovery_flow"
        case passwordlessFlow = "passwordless_flow"
        case sources
        case showSourceLabels = "show_source_labels"
        case pretendUserExists = "pretend_user_exists"
        case enableRememberMe = "enable_remember_me"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(userFields, forKey: .userFields)
        try container.encodeIfPresent(passwordStage, forKey: .passwordStage)
        try container.encodeIfPresent(captchaStage, forKey: .captchaStage)
        try container.encodeIfPresent(caseInsensitiveMatching, forKey: .caseInsensitiveMatching)
        try container.encodeIfPresent(showMatchedUser, forKey: .showMatchedUser)
        try container.encodeIfPresent(enrollmentFlow, forKey: .enrollmentFlow)
        try container.encodeIfPresent(recoveryFlow, forKey: .recoveryFlow)
        try container.encodeIfPresent(passwordlessFlow, forKey: .passwordlessFlow)
        try container.encodeIfPresent(sources, forKey: .sources)
        try container.encodeIfPresent(showSourceLabels, forKey: .showSourceLabels)
        try container.encodeIfPresent(pretendUserExists, forKey: .pretendUserExists)
        try container.encodeIfPresent(enableRememberMe, forKey: .enableRememberMe)
    }
}

