//
// LicenseFlagsEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum LicenseFlagsEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case trial = "trial"
    case nonProduction = "non_production"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
