//
// MatchingModeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum MatchingModeEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case strict = "strict"
    case regex = "regex"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
