//
// MicrosoftEntraProviderUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** MicrosoftEntraProviderUser Serializer */
public struct MicrosoftEntraProviderUserRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let microsoftIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var microsoftId: String
    public var user: Int
    public var provider: Int

    public init(microsoftId: String, user: Int, provider: Int) {
        self.microsoftId = microsoftId
        self.user = user
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case microsoftId = "microsoft_id"
        case user
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(microsoftId, forKey: .microsoftId)
        try container.encode(user, forKey: .user)
        try container.encode(provider, forKey: .provider)
    }
}

