//
// NetworkInterface.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct NetworkInterface: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: String
    public var hardwareAddress: String
    public var ipAddresses: [String]?
    public var dnsServers: [String]?

    public init(name: String, hardwareAddress: String, ipAddresses: [String]? = nil, dnsServers: [String]? = nil) {
        self.name = name
        self.hardwareAddress = hardwareAddress
        self.ipAddresses = ipAddresses
        self.dnsServers = dnsServers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case hardwareAddress = "hardware_address"
        case ipAddresses = "ip_addresses"
        case dnsServers = "dns_servers"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(hardwareAddress, forKey: .hardwareAddress)
        try container.encodeIfPresent(ipAddresses, forKey: .ipAddresses)
        try container.encodeIfPresent(dnsServers, forKey: .dnsServers)
    }
}

