//
// NotConfiguredActionEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum NotConfiguredActionEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case skip = "skip"
    case deny = "deny"
    case configure = "configure"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
