//
// OperatingSystem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OperatingSystem: Sendable, Codable, ParameterConvertible, Hashable {

    public var family: DeviceFactsOSFamily
    public var name: String?
    public var version: String?
    public var arch: String

    public init(family: DeviceFactsOSFamily, name: String? = nil, version: String? = nil, arch: String) {
        self.family = family
        self.name = name
        self.version = version
        self.arch = arch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case family
        case name
        case version
        case arch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(family, forKey: .family)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encode(arch, forKey: .arch)
    }
}

