//
// PatchedApplicationEntitlementRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** ApplicationEntitlement Serializer */
public struct PatchedApplicationEntitlementRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String?
    public var app: UUID?
    public var attributes: [String: JSONValue]?

    public init(name: String? = nil, app: UUID? = nil, attributes: [String: JSONValue]? = nil) {
        self.name = name
        self.app = app
        self.attributes = attributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case app
        case attributes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(app, forKey: .app)
        try container.encodeIfPresent(attributes, forKey: .attributes)
    }
}

