//
// PatchedMutualTLSStageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** MutualTLSStage Serializer */
public struct PatchedMutualTLSStageRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String?
    public var mode: StageModeEnum?
    /** Configure certificate authorities to validate the certificate against. This option has a higher priority than the `client_certificate` option on `Brand`. */
    public var certificateAuthorities: [UUID]?
    public var certAttribute: CertAttributeEnum?
    public var userAttribute: UserAttributeEnum?

    public init(name: String? = nil, mode: StageModeEnum? = nil, certificateAuthorities: [UUID]? = nil, certAttribute: CertAttributeEnum? = nil, userAttribute: UserAttributeEnum? = nil) {
        self.name = name
        self.mode = mode
        self.certificateAuthorities = certificateAuthorities
        self.certAttribute = certAttribute
        self.userAttribute = userAttribute
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case mode
        case certificateAuthorities = "certificate_authorities"
        case certAttribute = "cert_attribute"
        case userAttribute = "user_attribute"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(mode, forKey: .mode)
        try container.encodeIfPresent(certificateAuthorities, forKey: .certificateAuthorities)
        try container.encodeIfPresent(certAttribute, forKey: .certAttribute)
        try container.encodeIfPresent(userAttribute, forKey: .userAttribute)
    }
}

