//
// PermissionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Global permission */
public struct PermissionRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: 255, pattern: nil)
    public static let codenameRule = StringRule(minLength: 1, maxLength: 100, pattern: nil)
    public var name: String
    public var codename: String

    public init(name: String, codename: String) {
        self.name = name
        self.codename = codename
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case codename
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(codename, forKey: .codename)
    }
}

