//
// PromptStageRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** PromptStage Serializer */
public struct PromptStageRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var fields: [UUID]
    public var validationPolicies: [UUID]?

    public init(name: String, fields: [UUID], validationPolicies: [UUID]? = nil) {
        self.name = name
        self.fields = fields
        self.validationPolicies = validationPolicies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case fields
        case validationPolicies = "validation_policies"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(fields, forKey: .fields)
        try container.encodeIfPresent(validationPolicies, forKey: .validationPolicies)
    }
}

