//
// PropertyMappingTestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Test property mapping execution for a user/group with context */
public struct PropertyMappingTestRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var user: Int?
    public var context: [String: JSONValue]?
    public var group: UUID?

    public init(user: Int? = nil, context: [String: JSONValue]? = nil, group: UUID? = nil) {
        self.user = user
        self.context = context
        self.group = group
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case context
        case group
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(group, forKey: .group)
    }
}

