//
// StaticDeviceToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Serializer for static device&#39;s tokens */
public struct StaticDeviceToken: Sendable, Codable, ParameterConvertible, Hashable {

    public static let tokenRule = StringRule(minLength: nil, maxLength: 16, pattern: nil)
    public var token: String

    public init(token: String) {
        self.token = token
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
    }
}

