//
// SyncObjectResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Result of a single object sync */
public struct SyncObjectResult: Sendable, Codable, ParameterConvertible, Hashable {

    public var messages: [LogEvent]

    public init(messages: [LogEvent]) {
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(messages, forKey: .messages)
    }
}

