//
// SyncObjectRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Sync object serializer */
public struct SyncObjectRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let syncObjectIdRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var syncObjectModel: SyncObjectModelEnum
    public var syncObjectId: String
    public var overrideDryRun: Bool? = false

    public init(syncObjectModel: SyncObjectModelEnum, syncObjectId: String, overrideDryRun: Bool? = false) {
        self.syncObjectModel = syncObjectModel
        self.syncObjectId = syncObjectId
        self.overrideDryRun = overrideDryRun
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case syncObjectModel = "sync_object_model"
        case syncObjectId = "sync_object_id"
        case overrideDryRun = "override_dry_run"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(syncObjectModel, forKey: .syncObjectModel)
        try container.encode(syncObjectId, forKey: .syncObjectId)
        try container.encodeIfPresent(overrideDryRun, forKey: .overrideDryRun)
    }
}

