//
// TenantRecoveryKeyRequestRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Tenant recovery key creation request serializer */
public struct TenantRecoveryKeyRequestRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public static let userRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var user: String
    public var durationDays: Int

    public init(user: String, durationDays: Int) {
        self.user = user
        self.durationDays = durationDays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case durationDays = "duration_days"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encode(durationDays, forKey: .durationDays)
    }
}

