//
// UserCreationModeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UserCreationModeEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case neverCreate = "never_create"
    case createWhenRequired = "create_when_required"
    case alwaysCreate = "always_create"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
