//
// UserTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum UserTypeEnum: String, Sendable, Codable, CaseIterable, CaseIterableDefaultsLast {
    case _internal = "internal"
    case external = "external"
    case serviceAccount = "service_account"
    case internalServiceAccount = "internal_service_account"
    case unknownDefaultOpenApi = "unknown_default_open_api"
}
