//
// UserAccountSerializerForRoleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Account adding/removing operations */
public struct UserAccountSerializerForRoleRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var pk: Int

    public init(pk: Int) {
        self.pk = pk
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pk
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pk, forKey: .pk)
    }
}

