//
// AuthenticatorMobilePayloadChallenge.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Payload within the QR code given to the mobile app, hence the short variable names */
public struct AuthenticatorMobilePayloadChallenge: Codable, JSONEncodable, Hashable {

    /** Server URL */
    public var u: String?
    /** Stage UUID */
    public var s: String?
    /** Initial Token */
    public var t: String?

    public init(u: String? = nil, s: String? = nil, t: String? = nil) {
        self.u = u
        self.s = s
        self.t = t
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case u
        case s
        case t
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(u, forKey: .u)
        try container.encodeIfPresent(s, forKey: .s)
        try container.encodeIfPresent(t, forKey: .t)
    }
}

