//
// PatchedBlueprintInstanceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Info about a single blueprint instance file */
public struct PatchedBlueprintInstanceRequest: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var path: String? = ""
    public var context: AnyCodable?
    public var enabled: Bool?
    public var content: String?

    public init(name: String? = nil, path: String? = "", context: AnyCodable? = nil, enabled: Bool? = nil, content: String? = nil) {
        self.name = name
        self.path = path
        self.context = context
        self.enabled = enabled
        self.content = content
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case path
        case context
        case enabled
        case content
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(context, forKey: .context)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(content, forKey: .content)
    }
}

