//
// PatchedRACPropertyMappingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** RACPropertyMapping Serializer */
public struct PatchedRACPropertyMappingRequest: Codable, JSONEncodable, Hashable {

    /** Objects that are managed by authentik. These objects are created and updated automatically. This flag only indicates that an object can be overwritten by migrations. You can still modify the objects via the API, but expect changes to be overwritten in a later update. */
    public var managed: String?
    public var name: String?
    public var expression: String?
    public var staticSettings: [String: AnyCodable]?

    public init(managed: String? = nil, name: String? = nil, expression: String? = nil, staticSettings: [String: AnyCodable]? = nil) {
        self.managed = managed
        self.name = name
        self.expression = expression
        self.staticSettings = staticSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case managed
        case name
        case expression
        case staticSettings = "static_settings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(managed, forKey: .managed)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(expression, forKey: .expression)
        try container.encodeIfPresent(staticSettings, forKey: .staticSettings)
    }
}

